"""Add unique constrainsts to phone column

Revision ID: f354ab83c8b7
Revises: f440d4d43ec6
Create Date: 2022-08-08 15:03:32.549472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f354ab83c8b7'
down_revision = 'f440d4d43ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['phone'])
    op.create_unique_constraint(None, 'venues', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
